name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with: 
          upload-coverage: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
